name: GitHub Actions Demo

on:
  push:
    branches: [main]
    paths-ignore: [.github/**]
  pull_request:
    branches: [main]

  schedule:
    - cron: '15 6 * * SUN'
  workflow_dispatch:

jobs:
 Build:
   runs-on: ubuntu-latest
   steps:
     - run: |
         echo "The name of the trigger was ${{github.event_name}}"
    - users: action

  
